/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package final_pbo;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Bambang Sumadi
 */
public class viewUtama extends javax.swing.JFrame {

    /**
     * Creates new form viewUtama
     */
    public viewUtama() {
        initComponents();
    }
    public void peringatan(String pesan) {
        JOptionPane.showMessageDialog(rootPane, pesan);
    }
    ArrayList<SkripsiPOJO> Skripsi;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        panelKiri = new javax.swing.JPanel();
        jHome = new javax.swing.JButton();
        jBuku = new javax.swing.JButton();
        jSkripsi = new javax.swing.JButton();
        jSearch = new javax.swing.JButton();
        jKeluar = new javax.swing.JButton();
        panelAtas = new javax.swing.JPanel();
        panelTengah = new javax.swing.JPanel();
        panelHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pinjamBuku = new javax.swing.JButton();
        pinjamSkripsi = new javax.swing.JButton();
        panelBuku = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        isiID = new javax.swing.JTextField();
        isiNama = new javax.swing.JTextField();
        isiISBN = new javax.swing.JTextField();
        isiPengarang = new javax.swing.JTextField();
        isiAngkatan = new javax.swing.JTextField();
        isiJudul = new javax.swing.JTextField();
        isiPenerbit = new javax.swing.JTextField();
        isiTahun = new javax.swing.JTextField();
        isiHalaman = new javax.swing.JTextField();
        isiJumlah = new javax.swing.JTextField();
        isiSub = new javax.swing.JTextField();
        isiTgl = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        simpan = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        hapus1 = new javax.swing.JButton();
        jTextField13 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        peminjamanBuku = new javax.swing.JButton();
        panelSkripsi = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        isiID1 = new javax.swing.JTextField();
        isiNama1 = new javax.swing.JTextField();
        isiAngkatan1 = new javax.swing.JTextField();
        isiIDSkripsi = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        isiJudul1 = new javax.swing.JTextField();
        isiTahun1 = new javax.swing.JTextField();
        isiJumlah1 = new javax.swing.JTextField();
        isiTgl1 = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        update = new javax.swing.JButton();
        input = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField14 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        peminjamanSkripsi = new javax.swing.JButton();
        panelSearch = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelPinjamBuku = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        keluar = new javax.swing.JButton();
        panelPinjamSkripsi = new javax.swing.JPanel();
        exit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi IS Bibliography");
        setPreferredSize(new java.awt.Dimension(800, 480));

        mainPanel.setBackground(new java.awt.Color(248, 243, 230));
        mainPanel.setPreferredSize(new java.awt.Dimension(600, 520));

        panelKiri.setBackground(new java.awt.Color(248, 243, 230));

        jHome.setBackground(new java.awt.Color(248, 243, 230));
        jHome.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\primary (1).png")); // NOI18N
        jHome.setBorder(null);
        jHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHomeActionPerformed(evt);
            }
        });

        jBuku.setBackground(new java.awt.Color(248, 243, 230));
        jBuku.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\Vector.png")); // NOI18N
        jBuku.setBorder(null);
        jBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBukuActionPerformed(evt);
            }
        });

        jSkripsi.setBackground(new java.awt.Color(248, 243, 230));
        jSkripsi.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\Vector (1).png")); // NOI18N
        jSkripsi.setBorder(null);
        jSkripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSkripsiActionPerformed(evt);
            }
        });

        jSearch.setBackground(new java.awt.Color(248, 243, 230));
        jSearch.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\Vector (3).png")); // NOI18N
        jSearch.setBorder(null);
        jSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchActionPerformed(evt);
            }
        });

        jKeluar.setBackground(new java.awt.Color(248, 243, 230));
        jKeluar.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\Vector (2).png")); // NOI18N
        jKeluar.setBorder(null);

        javax.swing.GroupLayout panelKiriLayout = new javax.swing.GroupLayout(panelKiri);
        panelKiri.setLayout(panelKiriLayout);
        panelKiriLayout.setHorizontalGroup(
            panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKiriLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSkripsi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBuku, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jKeluar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelKiriLayout.setVerticalGroup(
            panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKiriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jHome, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSkripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        panelAtas.setBackground(new java.awt.Color(41, 134, 204));

        javax.swing.GroupLayout panelAtasLayout = new javax.swing.GroupLayout(panelAtas);
        panelAtas.setLayout(panelAtasLayout);
        panelAtasLayout.setHorizontalGroup(
            panelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelAtasLayout.setVerticalGroup(
            panelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        panelTengah.setBackground(new java.awt.Color(150, 213, 242));
        panelTengah.setLayout(new java.awt.CardLayout());

        panelHome.setBackground(new java.awt.Color(150, 213, 242));

        jLabel1.setBackground(new java.awt.Color(41, 134, 204));
        jLabel1.setFont(new java.awt.Font("Helvetica Rounded", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(5, 37, 132));
        jLabel1.setText("Home");

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\OBJECTS.png")); // NOI18N

        jLabel8.setBackground(new java.awt.Color(41, 134, 204));
        jLabel8.setFont(new java.awt.Font("Helvetica Rounded", 3, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(5, 37, 132));
        jLabel8.setText("Building a Comprehensive");

        jLabel9.setBackground(new java.awt.Color(41, 134, 204));
        jLabel9.setFont(new java.awt.Font("Helvetica", 3, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(5, 37, 132));
        jLabel9.setText("List of Book Titles Produced by Students");

        pinjamBuku.setBackground(new java.awt.Color(246, 246, 246));
        pinjamBuku.setFont(new java.awt.Font("Helvetica Rounded", 1, 18)); // NOI18N
        pinjamBuku.setForeground(new java.awt.Color(5, 37, 132));
        pinjamBuku.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\Vector.png")); // NOI18N
        pinjamBuku.setText("Book");
        pinjamBuku.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pinjamBuku.setIconTextGap(10);
        pinjamBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinjamBukuActionPerformed(evt);
            }
        });

        pinjamSkripsi.setBackground(new java.awt.Color(246, 246, 246));
        pinjamSkripsi.setFont(new java.awt.Font("Helvetica Rounded", 1, 18)); // NOI18N
        pinjamSkripsi.setForeground(new java.awt.Color(5, 37, 132));
        pinjamSkripsi.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\Vector (1).png")); // NOI18N
        pinjamSkripsi.setText("Skripsi");
        pinjamSkripsi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pinjamSkripsi.setIconTextGap(10);
        pinjamSkripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinjamSkripsiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1))
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(483, 483, 483)
                        .addComponent(jLabel8))
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(416, 416, 416)
                        .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))))
                .addContainerGap(408, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHomeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pinjamBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pinjamSkripsi)
                .addGap(508, 508, 508))
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(101, 101, 101)
                .addComponent(jLabel7)
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pinjamBuku)
                    .addComponent(pinjamSkripsi))
                .addContainerGap(206, Short.MAX_VALUE))
        );

        panelTengah.add(panelHome, "card2");

        panelBuku.setBackground(new java.awt.Color(150, 213, 242));
        panelBuku.setPreferredSize(new java.awt.Dimension(1213, 661));

        jLabel2.setBackground(new java.awt.Color(41, 134, 204));
        jLabel2.setFont(new java.awt.Font("Helvetica Rounded", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(5, 37, 132));
        jLabel2.setText("Book");

        jLabel10.setFont(new java.awt.Font("Helvetica Rounded", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 51));
        jLabel10.setText("ID");

        jPanel1.setBackground(new java.awt.Color(41, 134, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 4));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Helvetica Rounded", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 51));
        jLabel11.setText("Name");

        jLabel12.setFont(new java.awt.Font("Helvetica Rounded", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 51));
        jLabel12.setText("Gen");

        jLabel13.setFont(new java.awt.Font("Helvetica Rounded", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 51));
        jLabel13.setText("ISBN");

        jLabel14.setFont(new java.awt.Font("Helvetica Rounded", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 51));
        jLabel14.setText("Title");

        jLabel15.setFont(new java.awt.Font("Helvetica Rounded", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 51));
        jLabel15.setText("Author");

        jLabel16.setFont(new java.awt.Font("Helvetica Rounded", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 51));
        jLabel16.setText("Publish");

        jLabel17.setFont(new java.awt.Font("Helvetica Rounded", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 51));
        jLabel17.setText("Public year");

        jLabel18.setFont(new java.awt.Font("Helvetica Rounded", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 51, 51));
        jLabel18.setText("Categories");

        jLabel19.setFont(new java.awt.Font("Helvetica Rounded", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 51, 51));
        jLabel19.setText("NoP");

        jLabel20.setFont(new java.awt.Font("Helvetica Rounded", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 51, 51));
        jLabel20.setText("NoB");

        jLabel21.setFont(new java.awt.Font("Helvetica Rounded", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 51, 51));
        jLabel21.setText("Subtitle");

        jLabel22.setFont(new java.awt.Font("Helvetica Rounded", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 51, 51));
        jLabel22.setText("Date");

        isiID.setBackground(new java.awt.Color(246, 246, 246));
        isiID.setFont(new java.awt.Font("Helvetica Rounded", 1, 16)); // NOI18N
        isiID.setForeground(new java.awt.Color(246, 246, 246));

        isiNama.setBackground(new java.awt.Color(246, 246, 246));
        isiNama.setFont(new java.awt.Font("Helvetica Rounded", 1, 16)); // NOI18N
        isiNama.setForeground(new java.awt.Color(246, 246, 246));

        isiISBN.setBackground(new java.awt.Color(246, 246, 246));
        isiISBN.setFont(new java.awt.Font("Helvetica Rounded", 1, 16)); // NOI18N
        isiISBN.setForeground(new java.awt.Color(246, 246, 246));

        isiPengarang.setBackground(new java.awt.Color(246, 246, 246));
        isiPengarang.setFont(new java.awt.Font("Helvetica Rounded", 1, 16)); // NOI18N
        isiPengarang.setForeground(new java.awt.Color(246, 246, 246));

        isiAngkatan.setBackground(new java.awt.Color(246, 246, 246));
        isiAngkatan.setFont(new java.awt.Font("Helvetica Rounded", 1, 16)); // NOI18N
        isiAngkatan.setForeground(new java.awt.Color(246, 246, 246));

        isiJudul.setBackground(new java.awt.Color(246, 246, 246));
        isiJudul.setFont(new java.awt.Font("Helvetica Rounded", 1, 16)); // NOI18N
        isiJudul.setForeground(new java.awt.Color(246, 246, 246));

        isiPenerbit.setBackground(new java.awt.Color(246, 246, 246));
        isiPenerbit.setFont(new java.awt.Font("Helvetica Rounded", 1, 16)); // NOI18N
        isiPenerbit.setForeground(new java.awt.Color(246, 246, 246));

        isiTahun.setBackground(new java.awt.Color(246, 246, 246));
        isiTahun.setFont(new java.awt.Font("Helvetica Rounded", 1, 16)); // NOI18N
        isiTahun.setForeground(new java.awt.Color(246, 246, 246));
        isiTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isiTahunActionPerformed(evt);
            }
        });

        isiHalaman.setBackground(new java.awt.Color(246, 246, 246));
        isiHalaman.setFont(new java.awt.Font("Helvetica Rounded", 1, 16)); // NOI18N
        isiHalaman.setForeground(new java.awt.Color(246, 246, 246));

        isiJumlah.setBackground(new java.awt.Color(246, 246, 246));
        isiJumlah.setFont(new java.awt.Font("Helvetica Rounded", 1, 16)); // NOI18N
        isiJumlah.setForeground(new java.awt.Color(246, 246, 246));

        isiSub.setBackground(new java.awt.Color(246, 246, 246));
        isiSub.setFont(new java.awt.Font("Helvetica Rounded", 1, 16)); // NOI18N
        isiSub.setForeground(new java.awt.Color(246, 246, 246));

        isiTgl.setBackground(new java.awt.Color(246, 246, 246));
        isiTgl.setFont(new java.awt.Font("Helvetica Rounded", 1, 16)); // NOI18N
        isiTgl.setForeground(new java.awt.Color(246, 246, 246));

        jComboBox1.setBackground(new java.awt.Color(246, 246, 246));
        jComboBox1.setFont(new java.awt.Font("Helvetica Rounded", 1, 16)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 51, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Novel", "Magazine", "Dictionary", "Comic", "Encyclopedia", "Biography", "Manuscript", "Anthology" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Gen", "ISBN", "Title", "Author", "Publish", "Public year", "NoP", "NoB", "Categories", "Subtitle", "Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        simpan.setBackground(new java.awt.Color(41, 134, 204));
        simpan.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        simpan.setForeground(new java.awt.Color(255, 255, 255));
        simpan.setText("Save");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        edit.setBackground(new java.awt.Color(41, 134, 204));
        edit.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        edit.setForeground(new java.awt.Color(255, 255, 255));
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        hapus.setBackground(new java.awt.Color(41, 134, 204));
        hapus.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        hapus.setForeground(new java.awt.Color(255, 255, 255));
        hapus.setText("Delete");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        hapus1.setBackground(new java.awt.Color(41, 134, 204));
        hapus1.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        hapus1.setForeground(new java.awt.Color(255, 255, 255));
        hapus1.setText("Input");
        hapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus1ActionPerformed(evt);
            }
        });

        jTextField13.setBackground(new java.awt.Color(246, 246, 246));
        jTextField13.setFont(new java.awt.Font("Helvetica Rounded", 1, 16)); // NOI18N
        jTextField13.setForeground(new java.awt.Color(246, 246, 246));

        jComboBox2.setBackground(new java.awt.Color(246, 246, 246));
        jComboBox2.setFont(new java.awt.Font("Helvetica Rounded", 1, 16)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(0, 51, 51));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Novel", "Magazine", "Dictionary", "Comic", "Encyclopedia", "Biography", "Manuscript", "Anthology" }));

        jButton1.setBackground(new java.awt.Color(41, 134, 204));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\Page-1.png")); // NOI18N

        peminjamanBuku.setBackground(new java.awt.Color(248, 243, 230));
        peminjamanBuku.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        peminjamanBuku.setForeground(new java.awt.Color(255, 255, 255));
        peminjamanBuku.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\Vector.png")); // NOI18N
        peminjamanBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peminjamanBukuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBukuLayout = new javax.swing.GroupLayout(panelBuku);
        panelBuku.setLayout(panelBukuLayout);
        panelBukuLayout.setHorizontalGroup(
            panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBukuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBukuLayout.createSequentialGroup()
                        .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelBukuLayout.createSequentialGroup()
                        .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel10))
                        .addGap(34, 34, 34)
                        .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBukuLayout.createSequentialGroup()
                                .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(isiPengarang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(isiID)
                                        .addComponent(isiNama)
                                        .addComponent(isiAngkatan)
                                        .addComponent(isiISBN)
                                        .addComponent(isiJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelBukuLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel22))
                                    .addGroup(panelBukuLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel21))))
                                .addGap(18, 18, 18)
                                .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(isiTgl)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(isiPenerbit)
                                        .addComponent(isiTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(isiSub)
                                    .addComponent(isiHalaman)
                                    .addComponent(isiJumlah))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelBukuLayout.createSequentialGroup()
                                        .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23))
                                    .addGroup(panelBukuLayout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(198, 198, 198))))
                            .addGroup(panelBukuLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelBukuLayout.createSequentialGroup()
                                        .addComponent(peminjamanBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(simpan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(edit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(hapus)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(hapus1)))
                                .addGap(20, 20, 20))))))
            .addGroup(panelBukuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelBukuLayout.setVerticalGroup(
            panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBukuLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(peminjamanBuku, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel15)
                        .addGroup(panelBukuLayout.createSequentialGroup()
                            .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(isiID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)
                                .addComponent(jLabel10))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(isiNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17)
                                .addComponent(jLabel11))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(isiAngkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19)
                                .addComponent(jLabel12))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(isiISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20)
                                .addComponent(jLabel13))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel21)
                                .addComponent(isiJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(isiPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel22))))
                    .addGroup(panelBukuLayout.createSequentialGroup()
                        .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(isiPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isiTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isiHalaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isiJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBukuLayout.createSequentialGroup()
                                .addComponent(isiSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isiTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelBukuLayout.createSequentialGroup()
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        panelTengah.add(panelBuku, "card3");

        panelSkripsi.setBackground(new java.awt.Color(150, 213, 242));

        jLabel3.setBackground(new java.awt.Color(41, 134, 204));
        jLabel3.setFont(new java.awt.Font("Helvetica Rounded", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(5, 37, 132));
        jLabel3.setText("Skripsi");

        jPanel2.setBackground(new java.awt.Color(41, 134, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 4));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jLabel23.setFont(new java.awt.Font("Helvetica Rounded", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 51, 51));
        jLabel23.setText("ID");

        jLabel24.setFont(new java.awt.Font("Helvetica Rounded", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 51, 51));
        jLabel24.setText("Name");

        jLabel25.setFont(new java.awt.Font("Helvetica Rounded", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 51, 51));
        jLabel25.setText("Gen");

        jLabel26.setFont(new java.awt.Font("Helvetica Rounded", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 51, 51));
        jLabel26.setText("ID Skripsi");

        jLabel27.setFont(new java.awt.Font("Helvetica Rounded", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 51, 51));
        jLabel27.setText("Title");

        isiID1.setBackground(new java.awt.Color(246, 246, 246));
        isiID1.setFont(new java.awt.Font("Helvetica Rounded", 1, 16)); // NOI18N
        isiID1.setForeground(new java.awt.Color(246, 246, 246));

        isiNama1.setBackground(new java.awt.Color(246, 246, 246));
        isiNama1.setFont(new java.awt.Font("Helvetica Rounded", 1, 16)); // NOI18N
        isiNama1.setForeground(new java.awt.Color(246, 246, 246));

        isiAngkatan1.setBackground(new java.awt.Color(246, 246, 246));
        isiAngkatan1.setFont(new java.awt.Font("Helvetica Rounded", 1, 16)); // NOI18N
        isiAngkatan1.setForeground(new java.awt.Color(246, 246, 246));

        isiIDSkripsi.setBackground(new java.awt.Color(246, 246, 246));
        isiIDSkripsi.setFont(new java.awt.Font("Helvetica Rounded", 1, 16)); // NOI18N
        isiIDSkripsi.setForeground(new java.awt.Color(246, 246, 246));

        jLabel28.setFont(new java.awt.Font("Helvetica Rounded", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 51, 51));
        jLabel28.setText("Public year");

        jLabel29.setFont(new java.awt.Font("Helvetica Rounded", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 51, 51));
        jLabel29.setText("PoN");

        jLabel30.setFont(new java.awt.Font("Helvetica Rounded", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 51, 51));
        jLabel30.setText("Date");

        isiJudul1.setBackground(new java.awt.Color(246, 246, 246));
        isiJudul1.setFont(new java.awt.Font("Helvetica Rounded", 1, 16)); // NOI18N
        isiJudul1.setForeground(new java.awt.Color(246, 246, 246));

        isiTahun1.setBackground(new java.awt.Color(246, 246, 246));
        isiTahun1.setFont(new java.awt.Font("Helvetica Rounded", 1, 16)); // NOI18N
        isiTahun1.setForeground(new java.awt.Color(246, 246, 246));

        isiJumlah1.setBackground(new java.awt.Color(246, 246, 246));
        isiJumlah1.setFont(new java.awt.Font("Helvetica Rounded", 1, 16)); // NOI18N
        isiJumlah1.setForeground(new java.awt.Color(246, 246, 246));

        isiTgl1.setBackground(new java.awt.Color(246, 246, 246));
        isiTgl1.setFont(new java.awt.Font("Helvetica Rounded", 1, 16)); // NOI18N
        isiTgl1.setForeground(new java.awt.Color(246, 246, 246));

        save.setBackground(new java.awt.Color(41, 134, 204));
        save.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(41, 134, 204));
        update.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Edit");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        input.setBackground(new java.awt.Color(41, 134, 204));
        input.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        input.setForeground(new java.awt.Color(255, 255, 255));
        input.setText("Input");
        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(41, 134, 204));
        delete.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jComboBox3.setBackground(new java.awt.Color(246, 246, 246));
        jComboBox3.setFont(new java.awt.Font("Helvetica Rounded", 1, 16)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(0, 51, 51));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Novel", "Magazine", "Dictionary", "Comic", "Encyclopedia", "Biography", "Manuscript", "Anthology" }));

        jTextField14.setBackground(new java.awt.Color(246, 246, 246));
        jTextField14.setFont(new java.awt.Font("Helvetica Rounded", 1, 16)); // NOI18N
        jTextField14.setForeground(new java.awt.Color(246, 246, 246));

        jButton2.setBackground(new java.awt.Color(41, 134, 204));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\Page-1.png")); // NOI18N

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Gen", "ID Skripsi", "Title", "Public year", "PoN", "Date"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        peminjamanSkripsi.setBackground(new java.awt.Color(248, 243, 230));
        peminjamanSkripsi.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        peminjamanSkripsi.setForeground(new java.awt.Color(255, 255, 255));
        peminjamanSkripsi.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\Vector (1).png")); // NOI18N
        peminjamanSkripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peminjamanSkripsiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSkripsiLayout = new javax.swing.GroupLayout(panelSkripsi);
        panelSkripsi.setLayout(panelSkripsiLayout);
        panelSkripsiLayout.setHorizontalGroup(
            panelSkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSkripsiLayout.createSequentialGroup()
                .addGroup(panelSkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSkripsiLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(panelSkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSkripsiLayout.createSequentialGroup()
                                .addGroup(panelSkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelSkripsiLayout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addGap(53, 53, 53)
                                        .addComponent(isiNama1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelSkripsiLayout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                                        .addComponent(isiID1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelSkripsiLayout.createSequentialGroup()
                                        .addGroup(panelSkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelSkripsiLayout.createSequentialGroup()
                                                .addComponent(jLabel25)
                                                .addGap(69, 69, 69))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSkripsiLayout.createSequentialGroup()
                                                .addComponent(jLabel26)
                                                .addGap(18, 18, 18)))
                                        .addGroup(panelSkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(isiIDSkripsi, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(isiAngkatan1))))
                                .addGap(18, 18, 18)
                                .addGroup(panelSkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelSkripsiLayout.createSequentialGroup()
                                        .addGroup(panelSkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel30)
                                            .addComponent(jLabel29)
                                            .addComponent(jLabel27))
                                        .addGap(58, 58, 58))))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGroup(panelSkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSkripsiLayout.createSequentialGroup()
                                .addGap(0, 256, Short.MAX_VALUE)
                                .addComponent(peminjamanSkripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(update)
                                .addGap(12, 12, 12)
                                .addComponent(delete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelSkripsiLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(panelSkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelSkripsiLayout.createSequentialGroup()
                                        .addGroup(panelSkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(isiJumlah1)
                                            .addComponent(isiTgl1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(panelSkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBox3, 0, 220, Short.MAX_VALUE)
                                            .addComponent(jTextField14))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelSkripsiLayout.createSequentialGroup()
                                        .addGroup(panelSkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(isiTahun1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                                            .addComponent(isiJudul1))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(panelSkripsiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        panelSkripsiLayout.setVerticalGroup(
            panelSkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSkripsiLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelSkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(peminjamanSkripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panelSkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(isiID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isiJudul1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(isiNama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isiTahun1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelSkripsiLayout.createSequentialGroup()
                        .addGroup(panelSkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(isiAngkatan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isiJumlah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelSkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(isiIDSkripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isiTgl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addComponent(jLabel30)))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelTengah.add(panelSkripsi, "card4");

        panelSearch.setBackground(new java.awt.Color(150, 213, 242));

        jLabel4.setBackground(new java.awt.Color(41, 134, 204));
        jLabel4.setFont(new java.awt.Font("Helvetica Rounded", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(5, 37, 132));
        jLabel4.setText("Search");

        javax.swing.GroupLayout panelSearchLayout = new javax.swing.GroupLayout(panelSearch);
        panelSearch.setLayout(panelSearchLayout);
        panelSearchLayout.setHorizontalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addContainerGap(1070, Short.MAX_VALUE))
        );
        panelSearchLayout.setVerticalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addContainerGap(605, Short.MAX_VALUE))
        );

        panelTengah.add(panelSearch, "card5");

        panelPinjamBuku.setBackground(new java.awt.Color(150, 213, 242));

        jLabel5.setFont(new java.awt.Font("Helvetica Rounded", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(5, 37, 132));
        jLabel5.setText("Peminjaman Buku");

        keluar.setBackground(new java.awt.Color(150, 213, 242));
        keluar.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\Group 1876.png")); // NOI18N
        keluar.setBorder(null);
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPinjamBukuLayout = new javax.swing.GroupLayout(panelPinjamBuku);
        panelPinjamBuku.setLayout(panelPinjamBukuLayout);
        panelPinjamBukuLayout.setHorizontalGroup(
            panelPinjamBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPinjamBukuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(keluar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(972, Short.MAX_VALUE))
        );
        panelPinjamBukuLayout.setVerticalGroup(
            panelPinjamBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPinjamBukuLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelPinjamBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(keluar)
                    .addComponent(jLabel5))
                .addContainerGap(618, Short.MAX_VALUE))
        );

        panelTengah.add(panelPinjamBuku, "card6");

        panelPinjamSkripsi.setBackground(new java.awt.Color(150, 213, 242));

        exit.setBackground(new java.awt.Color(150, 213, 242));
        exit.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\Group 1876.png")); // NOI18N
        exit.setBorder(null);

        jLabel6.setFont(new java.awt.Font("Helvetica Rounded", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(5, 37, 132));
        jLabel6.setText("Peminjaman Skripsi");

        javax.swing.GroupLayout panelPinjamSkripsiLayout = new javax.swing.GroupLayout(panelPinjamSkripsi);
        panelPinjamSkripsi.setLayout(panelPinjamSkripsiLayout);
        panelPinjamSkripsiLayout.setHorizontalGroup(
            panelPinjamSkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPinjamSkripsiLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(exit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(957, Short.MAX_VALUE))
        );
        panelPinjamSkripsiLayout.setVerticalGroup(
            panelPinjamSkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPinjamSkripsiLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelPinjamSkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exit)
                    .addComponent(jLabel6))
                .addContainerGap(619, Short.MAX_VALUE))
        );

        panelTengah.add(panelPinjamSkripsi, "card7");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(panelKiri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTengah, javax.swing.GroupLayout.PREFERRED_SIZE, 1211, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(panelAtas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(panelAtas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelKiri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(panelTengah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1290, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 680, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHomeActionPerformed
        panelTengah.removeAll();
        panelTengah.repaint();
        panelTengah.revalidate();
        panelTengah.add(panelHome);
        panelTengah.repaint();
        panelTengah.revalidate();

    }//GEN-LAST:event_jHomeActionPerformed

    private void jBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBukuActionPerformed
        panelTengah.removeAll();
        panelTengah.repaint();
        panelTengah.revalidate();
        panelTengah.add(panelBuku);
        panelTengah.repaint();
        panelTengah.revalidate();
    }//GEN-LAST:event_jBukuActionPerformed

    private void jSkripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSkripsiActionPerformed
        panelTengah.removeAll();
        panelTengah.repaint();
        panelTengah.revalidate();
        panelTengah.add(panelSkripsi);
        panelTengah.repaint();
        panelTengah.revalidate();
    }//GEN-LAST:event_jSkripsiActionPerformed

    private void jSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchActionPerformed
        panelTengah.removeAll();
        panelTengah.repaint();
        panelTengah.revalidate();
        panelTengah.add(panelSearch);
        panelTengah.repaint();
        panelTengah.revalidate();
    }//GEN-LAST:event_jSearchActionPerformed

    private void pinjamBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinjamBukuActionPerformed
        panelTengah.removeAll();
        panelTengah.repaint();
        panelTengah.revalidate();
        panelTengah.add(panelPinjamBuku);
        panelTengah.repaint();
        panelTengah.revalidate();
    }//GEN-LAST:event_pinjamBukuActionPerformed

    private void pinjamSkripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinjamSkripsiActionPerformed
        panelHome.removeAll();
        panelHome.repaint();
        panelHome.revalidate();
        panelHome.add(panelPinjamSkripsi);
        panelHome.repaint();
        panelHome.revalidate();
    }//GEN-LAST:event_pinjamSkripsiActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        panelTengah.removeAll();
        panelTengah.repaint();
        panelTengah.revalidate();
        panelTengah.add(panelHome);
        panelTengah.repaint();
        panelTengah.revalidate();
    }//GEN-LAST:event_keluarActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simpanActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusActionPerformed

    private void hapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapus1ActionPerformed

    private void isiTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isiTahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isiTahunActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void peminjamanSkripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peminjamanSkripsiActionPerformed
        panelSkripsi.removeAll();
        panelSkripsi.repaint();
        panelSkripsi.revalidate();
        panelSkripsi.add(panelPinjamSkripsi);
        panelSkripsi.repaint();
        panelSkripsi.revalidate();
    }//GEN-LAST:event_peminjamanSkripsiActionPerformed

    private void peminjamanBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peminjamanBukuActionPerformed
        panelBuku.removeAll();
        panelBuku.repaint();
        panelBuku.revalidate();
        panelBuku.add(panelPinjamBuku);
        panelBuku.repaint();
        panelBuku.revalidate();
    }//GEN-LAST:event_peminjamanBukuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JButton exit;
    private javax.swing.JButton hapus;
    private javax.swing.JButton hapus1;
    private javax.swing.JButton input;
    private javax.swing.JTextField isiAngkatan;
    private javax.swing.JTextField isiAngkatan1;
    private javax.swing.JTextField isiHalaman;
    private javax.swing.JTextField isiID;
    private javax.swing.JTextField isiID1;
    private javax.swing.JTextField isiIDSkripsi;
    private javax.swing.JTextField isiISBN;
    private javax.swing.JTextField isiJudul;
    private javax.swing.JTextField isiJudul1;
    private javax.swing.JTextField isiJumlah;
    private javax.swing.JTextField isiJumlah1;
    private javax.swing.JTextField isiNama;
    private javax.swing.JTextField isiNama1;
    private javax.swing.JTextField isiPenerbit;
    private javax.swing.JTextField isiPengarang;
    private javax.swing.JTextField isiSub;
    private javax.swing.JTextField isiTahun;
    private javax.swing.JTextField isiTahun1;
    private javax.swing.JTextField isiTgl;
    private javax.swing.JTextField isiTgl1;
    private javax.swing.JButton jBuku;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JButton jHome;
    private javax.swing.JButton jKeluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jSearch;
    private javax.swing.JButton jSkripsi;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JButton keluar;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelAtas;
    private javax.swing.JPanel panelBuku;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelKiri;
    private javax.swing.JPanel panelPinjamBuku;
    private javax.swing.JPanel panelPinjamSkripsi;
    private javax.swing.JPanel panelSearch;
    private javax.swing.JPanel panelSkripsi;
    private javax.swing.JPanel panelTengah;
    private javax.swing.JButton peminjamanBuku;
    private javax.swing.JButton peminjamanSkripsi;
    private javax.swing.JButton pinjamBuku;
    private javax.swing.JButton pinjamSkripsi;
    private javax.swing.JButton save;
    private javax.swing.JButton simpan;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
